/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionCreateRouteImport } from './routes/session/create'
import { Route as SessionSessionIdRouteImport } from './routes/session/$sessionId'
import { Route as PartyCreateRouteImport } from './routes/party/create'
import { Route as PartyEditPartyIdRouteImport } from './routes/party/edit.$partyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCreateRoute = SessionCreateRouteImport.update({
  id: '/session/create',
  path: '/session/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyCreateRoute = PartyCreateRouteImport.update({
  id: '/party/create',
  path: '/party/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyEditPartyIdRoute = PartyEditPartyIdRouteImport.update({
  id: '/party/edit/$partyId',
  path: '/party/edit/$partyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/party/create': typeof PartyCreateRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/create': typeof SessionCreateRoute
  '/party/edit/$partyId': typeof PartyEditPartyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/party/create': typeof PartyCreateRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/create': typeof SessionCreateRoute
  '/party/edit/$partyId': typeof PartyEditPartyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/party/create': typeof PartyCreateRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/create': typeof SessionCreateRoute
  '/party/edit/$partyId': typeof PartyEditPartyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/party/create'
    | '/session/$sessionId'
    | '/session/create'
    | '/party/edit/$partyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/party/create'
    | '/session/$sessionId'
    | '/session/create'
    | '/party/edit/$partyId'
  id:
    | '__root__'
    | '/'
    | '/party/create'
    | '/session/$sessionId'
    | '/session/create'
    | '/party/edit/$partyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PartyCreateRoute: typeof PartyCreateRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  SessionCreateRoute: typeof SessionCreateRoute
  PartyEditPartyIdRoute: typeof PartyEditPartyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/create': {
      id: '/session/create'
      path: '/session/create'
      fullPath: '/session/create'
      preLoaderRoute: typeof SessionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/create': {
      id: '/party/create'
      path: '/party/create'
      fullPath: '/party/create'
      preLoaderRoute: typeof PartyCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/edit/$partyId': {
      id: '/party/edit/$partyId'
      path: '/party/edit/$partyId'
      fullPath: '/party/edit/$partyId'
      preLoaderRoute: typeof PartyEditPartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PartyCreateRoute: PartyCreateRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  SessionCreateRoute: SessionCreateRoute,
  PartyEditPartyIdRoute: PartyEditPartyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
